# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
  en: Harfang's Perch
  ko: Harfang's Perch
email: bonghyun.d.kim@gmail.com
description:
  en: On software in general, with focus on Ruby, Swift, Elixir
  ko: 소프트웨어 전반에 대한 개인 블로그. Ruby, Swift, Elixir 
index:
  en:
  ko: index_ko.html
feed:
  en: /feed.xml
  ko: /feed_ko.xml
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://harfangk.github.io" # the base hostname & protocol for your site
github_username:  harfangk
twitter_username: harfangk

paginate: 10

# Build settings
markdown: kramdown

gems: [jekyll-paginate]
